# tabelas/base/pocoes_data.py

POCOES_DATA = [
    {"d_min": 1, "d_max": 1, "nome_base": "Abençoar Alimentos",
        "descricao_completa": "Abençoar Alimentos (óleo)", "preco_ts": 30},
    {"d_min": 2, "d_max": 3, "nome_base": "Área Escorregadia",
        "descricao_completa": "Área Escorregadia (granada)", "preco_ts": 30},
    {"d_min": 4, "d_max": 6, "nome_base": "Arma Mágica",
        "descricao_completa": "Arma Mágica (óleo)", "preco_ts": 30},
    {"d_min": 7, "d_max": 7, "nome_base": "Compreensão",
        "descricao_completa": "Compreensão", "preco_ts": 30},
    {"d_min": 8, "d_max": 15, "nome_base": "Curar Ferimentos", "descricao_completa":
        "Curar Ferimentos (2d8+2 PV)", "efeito_detalhe": "2d8+2 PV", "preco_ts": 30},
    {"d_min": 16, "d_max": 18, "nome_base": "Disfarce Ilusório",
        "descricao_completa": "Disfarce Ilusório", "preco_ts": 30},
    {"d_min": 19, "d_max": 20, "nome_base": "Escuridão",
        "descricao_completa": "Escuridão (óleo)", "preco_ts": 30},
    {"d_min": 21, "d_max": 22, "nome_base": "Luz",
        "descricao_completa": "Luz (óleo)", "preco_ts": 30},
    {"d_min": 23, "d_max": 24, "nome_base": "Névoa",
        "descricao_completa": "Névoa (granada)", "preco_ts": 30},
    {"d_min": 25, "d_max": 26, "nome_base": "Primor Atlético",
        "descricao_completa": "Primor Atlético", "preco_ts": 30},
    {"d_min": 27, "d_max": 28, "nome_base": "Proteção Divina",
        "descricao_completa": "Proteção Divina", "preco_ts": 30},
    {"d_min": 29, "d_max": 30, "nome_base": "Resistência a Energia",
        "descricao_completa": "Resistência a Energia", "preco_ts": 30},
    {"d_min": 31, "d_max": 32, "nome_base": "Sono",
        "descricao_completa": "Sono", "preco_ts": 30},
    {"d_min": 33, "d_max": 33, "nome_base": "Suporte Ambiental",
        "descricao_completa": "Suporte Ambiental", "preco_ts": 30},
    {"d_min": 34, "d_max": 34, "nome_base": "Tranca Arcana",
        "descricao_completa": "Tranca Arcana (óleo)", "preco_ts": 30},
    {"d_min": 35, "d_max": 35, "nome_base": "Visão Mística",
        "descricao_completa": "Visão Mística", "preco_ts": 30},
    {"d_min": 36, "d_max": 36, "nome_base": "Vitalidade Fantasma",
        "descricao_completa": "Vitalidade Fantasma", "preco_ts": 30},
    {"d_min": 37, "d_max": 38, "nome_base": "Escudo da Fé",
        "descricao_completa": "Escudo da Fé (aprimoramento para duração cena)", "preco_ts": 120},
    {"d_min": 39, "d_max": 40, "nome_base": "Alterar Tamanho",
        "descricao_completa": "Alterar Tamanho", "preco_ts": 270},
    {"d_min": 41, "d_max": 42, "nome_base": "Aparência Perfeita",
        "descricao_completa": "Aparência Perfeita", "preco_ts": 270},
    {"d_min": 43, "d_max": 43, "nome_base": "Armamento da Natureza",
        "descricao_completa": "Armamento da Natureza (óleo)", "preco_ts": 270},
    {"d_min": 44, "d_max": 49, "nome_base": "Bola de Fogo",
        "descricao_completa": "Bola de Fogo (granada)", "preco_ts": 270},
    {"d_min": 50, "d_max": 51, "nome_base": "Camuflagem Ilusória",
        "descricao_completa": "Camuflagem Ilusória", "preco_ts": 270},
    {"d_min": 52, "d_max": 53, "nome_base": "Concentração de Combate",
        "descricao_completa": "Concentração de Combate (aprimoramento para duração cena)", "preco_ts": 270},
    {"d_min": 54, "d_max": 62, "nome_base": "Curar Ferimentos", "descricao_completa":
        "Curar Ferimentos (4d8+4 PV)", "efeito_detalhe": "4d8+4 PV", "preco_ts": 270},
    {"d_min": 63, "d_max": 66, "nome_base": "Físico Divino",
        "descricao_completa": "Físico Divino", "preco_ts": 270},
    {"d_min": 67, "d_max": 68, "nome_base": "Mente Divina",
        "descricao_completa": "Mente Divina", "preco_ts": 270},
    {"d_min": 69, "d_max": 70, "nome_base": "Metamorfose",
        "descricao_completa": "Metamorfose", "preco_ts": 270},
    {"d_min": 71, "d_max": 75, "nome_base": "Purificação",
        "descricao_completa": "Purificação", "preco_ts": 270},
    {"d_min": 76, "d_max": 77, "nome_base": "Velocidade",
        "descricao_completa": "Velocidade", "preco_ts": 270},
    {"d_min": 78, "d_max": 79, "nome_base": "Vestimenta da Fé",
        "descricao_completa": "Vestimenta da Fé (óleo)", "preco_ts": 270},
    {"d_min": 80, "d_max": 80, "nome_base": "Voz Divina",
        "descricao_completa": "Voz Divina", "preco_ts": 270},
    {"d_min": 81, "d_max": 82, "nome_base": "Arma Mágica", "descricao_completa":
        "Arma Mágica (óleo; aprimoramento para bônus +3)", "efeito_detalhe": "bônus +3", "preco_ts": 750},
    {"d_min": 83, "d_max": 88, "nome_base": "Curar Ferimentos", "descricao_completa":
        "Curar Ferimentos (7d8+7 PV)", "efeito_detalhe": "7d8+7 PV", "preco_ts": 1080},
    {"d_min": 89, "d_max": 89, "nome_base": "Físico Divino",
        "descricao_completa": "Físico Divino (aprimoramento para três atributos)", "preco_ts": 1080},
    {"d_min": 90, "d_max": 92, "nome_base": "Invisibilidade",
        "descricao_completa": "Invisibilidade (aprimoramento para duração cena)", "preco_ts": 1080},
    {"d_min": 93, "d_max": 96, "nome_base": "Bola de Fogo", "descricao_completa":
        "Bola de Fogo (granada; aprimoramento para 10d6 de dano)", "efeito_detalhe": "10d6 dano", "preco_ts": 1470},
    {"d_min": 97, "d_max": 100, "nome_base": "Curar Ferimentos", "descricao_completa":
        "Curar Ferimentos (11d8+11 PV)", "efeito_detalhe": "11d8+11 PV", "preco_ts": 3000}
]
