# tabelas/base/tabela_8_4_data.py

EQUIPAMENTO_DATA = {
    "armas": [
        {"d_min": 1, "d_max": 3, "item": "Adaga"},
        {"d_min": 4, "d_max": 5, "item": "Alabarda"},
        {"d_min": 6, "d_max": 7, "item": "Alfange"},
        {"d_min": 8, "d_max": 10, "item": "Arco curto"},
        {"d_min": 11, "d_max": 13, "item": "Arco longo"},
        {"d_min": 14, "d_max": 15, "item": "Azagaia"},
        {"d_min": 16, "d_max": 16, "item": "Balas", "quantidade": 20},
        {"d_min": 17, "d_max": 18, "item": "Besta leve"},
        {"d_min": 19, "d_max": 20, "item": "Besta pesada"},
        {"d_min": 21, "d_max": 23, "item": "Bordão"},
        {"d_min": 24, "d_max": 24, "item": "Chicote"},
        {"d_min": 25, "d_max": 27, "item": "Cimitarra"},
        {"d_min": 28, "d_max": 30, "item": "Clava"},
        {"d_min": 31, "d_max": 31, "item": "Corrente de espinhos"},
        {"d_min": 32, "d_max": 33, "item": "Espada bastarda"},
        {"d_min": 34, "d_max": 38, "item": "Espada curta"},
        {"d_min": 39, "d_max": 43, "item": "Espada longa"},
        {"d_min": 44, "d_max": 46, "item": "Flechas", "quantidade": 20},
        {"d_min": 47, "d_max": 49, "item": "Florete"},
        {"d_min": 50, "d_max": 51, "item": "Foice"},
        {"d_min": 52, "d_max": 53, "item": "Funda"},
        {"d_min": 54, "d_max": 55, "item": "Gadanho"},
        {"d_min": 56, "d_max": 56, "item": "Katana"},
        {"d_min": 57, "d_max": 59, "item": "Lança"},
        {"d_min": 60, "d_max": 60, "item": "Lança montada"},
        {"d_min": 61, "d_max": 63, "item": "Maça"},
        {"d_min": 64, "d_max": 66, "item": "Machadinha"},
        {"d_min": 67, "d_max": 67, "item": "Machado anão"},
        {"d_min": 68, "d_max": 70, "item": "Machado de batalha"},
        {"d_min": 71, "d_max": 73, "item": "Machado de guerra"},
        {"d_min": 74, "d_max": 74, "item": "Machado táurico"},
        {"d_min": 75, "d_max": 76, "item": "Mangual"},
        {"d_min": 77, "d_max": 77, "item": "Marreta"},
        {"d_min": 78, "d_max": 80, "item": "Martelo de guerra"},
        {"d_min": 81, "d_max": 83, "item": "Montante"},
        {"d_min": 84, "d_max": 84, "item": "Mosquete"},
        {"d_min": 85, "d_max": 85, "item": "Pedras", "quantidade": 20},
        {"d_min": 86, "d_max": 88, "item": "Picareta"},
        {"d_min": 89, "d_max": 90, "item": "Pique"},
        {"d_min": 91, "d_max": 92, "item": "Pistola"},
        {"d_min": 93, "d_max": 93, "item": "Rede"},
        {"d_min": 94, "d_max": 96, "item": "Tacape"},
        {"d_min": 97, "d_max": 98, "item": "Tridente"},
        {"d_min": 99, "d_max": 100, "item": "Virotes", "quantidade": 20}
    ],
    "armaduras_escudos": [
        {"d_min": 1, "d_max": 5, "item": "Couro"},
        {"d_min": 6, "d_max": 10, "item": "Brunea"},
        {"d_min": 11, "d_max": 25, "item": "Completa"},  # Armadura Completa
        {"d_min": 26, "d_max": 30, "item": "Cota de malha"},
        {"d_min": 31, "d_max": 45, "item": "Couraça"},
        {"d_min": 46, "d_max": 55, "item": "Couro batido"},
        {"d_min": 56, "d_max": 65, "item": "Escudo leve"},
        {"d_min": 66, "d_max": 80, "item": "Escudo pesado"},
        {"d_min": 81, "d_max": 85, "item": "Gibão de peles"},
        {"d_min": 86, "d_max": 90, "item": "Loriga segmentada"},
        {"d_min": 91, "d_max": 100, "item": "Meia armadura"}
    ],
    "esotericos": [
        {"d_min": 1, "d_max": 10, "item": "Bolsa de pó"},
        {"d_min": 11, "d_max": 25, "item": "Cajado arcano"},
        {"d_min": 26, "d_max": 35, "item": "Cetro elemental"},
        {"d_min": 36, "d_max": 42, "item": "Costela de lich"},
        {"d_min": 43, "d_max": 50, "item": "Dedo de ente"},
        {"d_min": 51, "d_max": 55, "item": "Luva de ferro"},
        {"d_min": 56, "d_max": 65, "item": "Medalhão de prata"},
        {"d_min": 66, "d_max": 75, "item": "Orbe cristalina"},
        {"d_min": 76, "d_max": 85, "item": "Tomo hermético"},
        {"d_min": 86, "d_max": 100, "item": "Varinha arcana"}
    ]
}
