# tabelas/base/tabela_8_8_data.py

ARMAS_MAGICAS_ENCANTOS_DATA = [
    {"d_min": 1, "d_max": 5, "encanto": "Ameaçadora",
        "efeito": "Duplica margem de ameaça"},
    {"d_min": 6, "d_max": 10, "encanto": "Anticriatura",
        "efeito": "Bônus contra tipo de criatura"},
    {"d_min": 11, "d_max": 12, "encanto": "Arremesso",
        "efeito": "Pode ser arremessada"},
    {"d_min": 13, "d_max": 14, "encanto": "Assassina",
        "efeito": "Aumenta ataque furtivo"},
    {"d_min": 15, "d_max": 16, "encanto": "Caçadora",
        "efeito": "Ignora camuflagem leve e total e cobertura leve"},
    {"d_min": 17, "d_max": 21, "encanto": "Congelante",
        "efeito": "+1d6 de dano de frio"},
    {"d_min": 22, "d_max": 23, "encanto": "Conjuradora",
        "efeito": "Pode guardar e lançar magias"},
    {"d_min": 24, "d_max": 28, "encanto": "Corrosiva",
        "efeito": "+1d6 de dano de ácido"},
    {"d_min": 29, "d_max": 30, "encanto": "Dançarina", "efeito": "Ataca sozinha"},
    {"d_min": 31, "d_max": 34, "encanto": "Defensora", "efeito": "Defesa +2"},
    {"d_min": 35, "d_max": 36, "encanto": "Destruidora",
        "efeito": "Bônus contra construtos"},
    {"d_min": 37, "d_max": 38, "encanto": "Dilacerante",
        "efeito": "+10 de dano em acertos críticos"},
    {"d_min": 39, "d_max": 40, "encanto": "Drenante",
        "efeito": "Crítico drena vítima"},
    {"d_min": 41, "d_max": 45, "encanto": "Elétrica",
        "efeito": "+1d6 de dano de eletricidade"},
    {"d_min": 46, "d_max": 46, "encanto": "Energética",
        "efeito": "Bônus em ataque", "custo_encantos": 2, "reroll_se_menor": True},
    {"d_min": 47, "d_max": 48, "encanto": "Excruciante", "efeito": "Causa fraqueza"},
    {"d_min": 49, "d_max": 53, "encanto": "Flamejante",
        "efeito": "+1d6 de dano de fogo"},
    {"d_min": 54, "d_max": 63, "encanto": "Formidável",
        "efeito": "Ataque e dano +2"},  # Custo 1, bônus +2
    {"d_min": 64, "d_max": 64, "encanto": "Lancinante",
        "efeito": "Causa crítico terrível", "custo_encantos": 2, "reroll_se_menor": True},
    {"d_min": 65, "d_max": 72, "encanto": "Magnífica", "efeito": "Ataque e dano +4",
        "custo_encantos": 2, "reroll_se_menor": True},  # Custo 2, bônus +4
    {"d_min": 73, "d_max": 74, "encanto": "Piedosa", "efeito": "Dano não letal"},
    {"d_min": 75, "d_max": 76, "encanto": "Profana",
        "efeito": "Bônus contra devotos do Bem"},
    {"d_min": 77, "d_max": 78, "encanto": "Sagrada",
        "efeito": "Bônus contra devotos do Mal"},
    {"d_min": 79, "d_max": 80, "encanto": "Sanguinária",
        "efeito": "Causa sangramento"},
    {"d_min": 81, "d_max": 82, "encanto": "Trovejante",
        "efeito": "Causa atordoamento"},
    {"d_min": 83, "d_max": 84, "encanto": "Tumular",
        "efeito": "+1d8 de dano de trevas"},
    {"d_min": 85, "d_max": 88, "encanto": "Veloz", "efeito": "Fornece ataque extra"},
    {"d_min": 89, "d_max": 90, "encanto": "Venenosa",
        "efeito": "Causa envenenamento"},
    {"d_min": 91, "d_max": 100, "encanto": "Arma específica",
        "efeito": "Veja a Tabela 8-9", "referencia_tabela": "8-9"}
]
