# tabelas/base/tabela_8_3_data.py

ITENS_DIVERSOS_DATA = [
    {"d_min": 1, "d_max": 2, "item": "Ácido"},
    {"d_min": 3, "d_max": 4, "item": "Água benta"},
    {"d_min": 5, "d_max": 5, "item": "Alaúde élfico"},
    {"d_min": 6, "d_max": 6, "item": "Algemas"},
    {"d_min": 7, "d_max": 8, "item": "Baga-de-fogo"},
    {"d_min": 9, "d_max": 23, "item": "Bálsamo restaurador"},
    {"d_min": 24, "d_max": 24, "item": "Bandana"},
    {"d_min": 25, "d_max": 25, "item": "Bandoleira de poções"},
    {"d_min": 26, "d_max": 30, "item": "Bomba"},
    {"d_min": 31, "d_max": 31, "item": "Botas reforçadas"},
    {"d_min": 32, "d_max": 32, "item": "Camisa bufante"},
    {"d_min": 33, "d_max": 33, "item": "Capa esvoaçante"},
    {"d_min": 34, "d_max": 34, "item": "Capa pesada"},
    {"d_min": 35, "d_max": 35, "item": "Casaco longo"},
    {"d_min": 36, "d_max": 36, "item": "Chapéu arcano"},
    {"d_min": 37, "d_max": 38, "item": "Coleção de livros"},
    {"d_min": 39, "d_max": 40, "item": "Cosmético"},
    {"d_min": 41, "d_max": 42, "item": "Dente-de-dragão"},
    {"d_min": 43, "d_max": 43, "item": "Enfeite de elmo"},
    {"d_min": 44, "d_max": 44, "item": "Elixir do amor"},
    {"d_min": 45, "d_max": 46, "item": "Equipamento de viagem"},
    {"d_min": 47, "d_max": 56, "item": "Essência de mana"},
    {"d_min": 57, "d_max": 57, "item": "Estojo de disfarces"},
    {"d_min": 58, "d_max": 58, "item": "Farrapos de ermitão"},
    {"d_min": 59, "d_max": 59, "item": "Flauta mística"},
    {"d_min": 60, "d_max": 66, "item": "Fogo alquímico"},
    {"d_min": 67, "d_max": 67, "item": "Gorro de ervas"},
    {"d_min": 68, "d_max": 69, "item": "Líquen lilás"},
    {"d_min": 70, "d_max": 70, "item": "Luneta"},
    {"d_min": 71, "d_max": 71, "item": "Luva de pelica"},
    {"d_min": 72, "d_max": 73, "item": "Maleta de medicamentos"},
    {"d_min": 74, "d_max": 74, "item": "Manopla"},
    {"d_min": 75, "d_max": 75, "item": "Manto eclesiástico"},
    {"d_min": 76, "d_max": 78, "item": "Mochila de aventureiro"},
    {"d_min": 79, "d_max": 80, "item": "Musgo púrpura"},
    {"d_min": 81, "d_max": 81, "item": "Organizador de pergaminhos"},
    {"d_min": 82, "d_max": 83, "item": "Ossos de monstro"},
    {"d_min": 84, "d_max": 85, "item": "Pó de cristal"},
    {"d_min": 86, "d_max": 87, "item": "Pó de giz"},
    {"d_min": 88, "d_max": 88, "item": "Pó do desaparecimento"},
    {"d_min": 89, "d_max": 89, "item": "Robe místico"},
    {"d_min": 90, "d_max": 91, "item": "Saco de sal"},
    {"d_min": 92, "d_max": 92, "item": "Sapatos de camurça"},
    {"d_min": 93, "d_max": 94, "item": "Seixo de âmbar"},
    {"d_min": 95, "d_max": 95, "item": "Sela"},
    {"d_min": 96, "d_max": 96, "item": "Tabardo"},
    {"d_min": 97, "d_max": 97, "item": "Traje da corte"},
    {"d_min": 98, "d_max": 99, "item": "Terra de cemitério"},
    {"d_min": 100, "d_max": 100, "item": "Veste de seda"}
]
